### ISSUE TITLE
"IDAFrida" menu does not appear in ida.

### ISSUE THREAD

**Issue by daeinlee** [P4nda0s/IDAFrida#6]
hello.
Even if I put the IDAFrida.py file in the plugins folder, the "IDAFrida" menu does not appear in ida. 
Can you tell if the installation is wrong?
I checked in two versions, 7.1 and 7.7.
The error message is as below.

C:\Program Files\IDA 7.1\plugins\IDAFrida.py: invalid syntax (C:/Program Files/IDA 7.1/plugins/IDAFrida.py, line 114)
Traceback (most recent call last):
  File "C:\Program Files\IDA 7.1\python\ida_idaapi.py", line 566, in IDAPython_ExecScript
    execfile(script, g)
  File "C:/Program Files/IDA 7.1/plugins/IDAFrida.py", line 114
    def __init__(self) -> None:
                       ^
SyntaxError: invalid syntax

**Comment by Humenger** [comment]
So far only tested in 7.6, probably github transcoding, you can test this, it is directly from my IDA directory copied:  
[IDAFrida.zip](https://github.com/P4nda0s/IDAFrida/files/10998631/IDAFrida.zip)

**Comment by daeinlee** [comment]
Thank you for your concern.
Test result "IDA_Pro_7.7_Portable\IDA_Pro_7.7_Portable\plugins\IDAFrida.py: DLL load failed while importing sip" These errors occur.
I don't have the time right now, so I'll test it in a different environment when I can afford it.
Thanks for making such a nice tool.

**Comment by Humenger** [comment]
You can find the solution here: https://github.com/igogo-x86/HexRaysPyTools/issues/48
